### ISSUE TITLE
Extending actions in CAS Webflows (CAS 5.0.1)

### ISSUE THREAD

**Issue by nextigy** [apereo/cas-gradle-overlay-template#5]
Hello,

As part of our project we must redirect the logged user on the license agreement page.

The _login-webflow.xml_ has been modified in order to create a new action and corresponding view.

Based on the next example https://apereo.github.io/2016/10/07/webflow-extcfg/ the class action has been set up with Configuration/Configurer classes.

It seems that the Spring not take in effect the configuration file without _spring.factories_ file in _ressources/META-INF_ directory.

So it has been putted on with next line:
_org.springframework.boot.autoconfigure.EnableAutoConfiguration=com.test.SomethingConfiguration_

However, the next error message began to appear:
_2016-12-23 12:53:16,774 DEBUG [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Returning cached instance of singleton bean 'org.springframework.boot.autoconfigure.condition.BeanTypeRegistry'>
Exception in thread "main" java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.NoClassDefFoundError: org/springframework/webflow/execution/Action
        at java.lang.Class.getDeclaredMethods0(Native Method)
...
2016-12-23 12:53:16,795 ERROR [org.springframework.boot.SpringApplication] - <Application startup failed>
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:501)
        at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1189)java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.actuate.autoconfigure.AuditAutoConfiguratio
n$AuditEventRepositoryConfiguration due to org/springframework/webflow/execution/Action not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @C
omponentScan in the default package by mistake)
...
2016-12-23 12:53:16,802 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception thrown from LifecycleProcessor on context close>
java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@701fc37a: startup date [Fri Dec 23
12:53:09 CET 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@25618e91
      at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:417) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
...
2016-12-23 12:53:16,803 ERROR [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception>
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@701fc37a: startup date [Fri Dec 2
3 12:53:09 CET 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@25618e91
    at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]_

The bean tag in the deployerConfigContext.xml file without configuration class causes the same issue but with next error message:
2_016-12-23 12:48:57,094 ERROR [org.springframework.boot.SpringApplication] - <Application startup failed>
java.lang.IllegalStateException: Error processing condition on org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration
…
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.test.AccountCguAction] for bean with name 'accountCguAction' defined in class path resource [deployerConfigContext.xml]: problem with class file or dependent c
lass; nested exception is java.lang.NoClassDefFoundError: org/springframework/webflow/action/AbstractAction_

Dependency list of the build.gradle file :
```
dependencies {
    compile "org.apereo.cas:cas-server-webapp:${project.'cas.version'}@war"
    compile "org.apereo.cas:cas-server-core-webflow:${project.'cas.version'}"
}
```

The content of the AccountCguAction.java :
```
public final class AccountCguAction extends AbstractAction {
    protected Event doExecute(final RequestContext context) throws Exception {
        return result("success");
    }
}
```

The configuration of the login-webflow.xml
```
<!-- Existing action -->
<action-state id="realSubmit">
     ...
     <!--<transition on="success" to="sendTicketGrantingTicket"/>-->
     <transition on="success" to="cguCheck"/>
     ...
</action-state>
<!-- Added action -->
<action-state id="cguCheck">
     <evaluate expression="accountCguAction"/>
</action-state>
```

The modification of the “cas.webflow.autoconfigure” in properties file has no effects in this case.

Is at an issue or there is an error in configuration of the overlay based on the CAS 5.0.1 version?

Thank you in advance.

Regards

**Comment by mmoayyed** [comment]
Please use the CAS mailing list.
